### ISSUE TITLE
Определить стэк технологий необходимый для проекта

### ISSUE THREAD

**Issue by lexantus** [usestrict-js/rosseti-wind#3]
Написать какие библиотеки интересны, нравятся, хотелось бы попробовать:

[Маленький хитпарад библиотек] (https://www.codeinwp.com/blog/react-ui-component-libraries-frameworks/)

**Comment by Nikita-Fed** [comment]
**React Admin** - вроде симпатичный и есть бесплатная версия. Правда не очень понял можно ли на нем делать всякие кнопки для симулятора нашего электрического.
**React Bootstrap** - большое количество всяких компонентов, судя по всему очень популярная, видимо не просто так. и ничего не нашел про деньги, явно можно бесплатно использовать в отличие от Shards например.
**Blueprint** - тоже понравился. Большой выбор всего

**Comment by lexantus** [comment]
Принято - сегодня начну прикручивать

**Comment by lexantus** [comment]
Прикрутил Blueprint
